create table if not exists public.local_welfare_region_queue (
  id bigint generated by default as identity primary key,
  region text not null,
  sub_region text not null,
  area_detail text not null default '',
  source_prefix text not null,
  seed_urls jsonb not null default '[]'::jsonb,
  seed_titles jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'active', 'paused', 'done')),
  priority integer not null default 100,
  fail_count integer not null default 0,
  last_error text,
  last_checked_at timestamptz,
  next_check_at timestamptz,
  activated_by_report_started_at timestamptz,
  activated_by_report_finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (region, sub_region, area_detail)
);

create index if not exists idx_local_welfare_region_queue_status_priority
  on public.local_welfare_region_queue (status, priority, id);

create index if not exists idx_local_welfare_region_queue_next_check
  on public.local_welfare_region_queue (next_check_at);

create or replace function public.set_local_welfare_region_queue_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_local_welfare_region_queue_updated_at on public.local_welfare_region_queue;
create trigger trg_local_welfare_region_queue_updated_at
before update on public.local_welfare_region_queue
for each row execute function public.set_local_welfare_region_queue_updated_at();

alter table public.local_welfare_region_queue enable row level security;

drop policy if exists "service_role full access on local_welfare_region_queue" on public.local_welfare_region_queue;
create policy "service_role full access on local_welfare_region_queue"
on public.local_welfare_region_queue
for all
to service_role
using (true)
with check (true);

grant usage on schema public to service_role;
grant select, insert, update, delete on public.local_welfare_region_queue to service_role;
grant usage, select on sequence public.local_welfare_region_queue_id_seq to service_role;

insert into public.local_welfare_region_queue
  (region, sub_region, area_detail, source_prefix, seed_urls, seed_titles, status, priority)
values
  (
    '경기', '성남시', '', '성남시',
    '["https://www.seongnam.go.kr/city/1000216/10120/contents.do"]'::jsonb,
    '{"https://www.seongnam.go.kr/city/1000216/10120/contents.do":"노인복지"}'::jsonb,
    'active', 10
  ),
  (
    '서울', '강북구', '', '강북구',
    '["https://www.gangbuk.go.kr/welfare/main.do"]'::jsonb,
    '{"https://www.gangbuk.go.kr/welfare/main.do":"강북구 복지포털"}'::jsonb,
    'active', 20
  ),
  (
    '경기', '수원시', '', '수원시',
    '["https://www.suwon.go.kr/web/welfare/BD_boardList.do?bbsCd=1003"]'::jsonb,
    '{"https://www.suwon.go.kr/web/welfare/BD_boardList.do?bbsCd=1003":"노인복지"}'::jsonb,
    'active', 30
  ),
  (
    '경기', '부천시', '', '부천시',
    '["https://www.bucheon.go.kr/site/homepage/menu/viewMenu?menuid=148006003005004"]'::jsonb,
    '{"https://www.bucheon.go.kr/site/homepage/menu/viewMenu?menuid=148006003005004":"기초연금"}'::jsonb,
    'active', 40
  ),
  (
    '충북', '청주시', '', '청주시',
    '["https://cheongju.go.kr/bokji/index.do"]'::jsonb,
    '{"https://cheongju.go.kr/bokji/index.do":"청주시청 복지국"}'::jsonb,
    'active', 50
  ),
  (
    '전북', '전주시', '', '전주시',
    '["https://www.jeonju.go.kr/index.9is?contentUid=9be517a7914528ce01953583f9047544"]'::jsonb,
    '{"https://www.jeonju.go.kr/index.9is?contentUid=9be517a7914528ce01953583f9047544":"어르신 지원 경제적 지원"}'::jsonb,
    'pending', 60
  ),
  (
    '경남', '창원시', '', '창원시',
    '["http://www.changwon.go.kr/cwportal/depart/11067/14022/14044.web"]'::jsonb,
    '{"http://www.changwon.go.kr/cwportal/depart/11067/14022/14044.web":"기초연금"}'::jsonb,
    'pending', 70
  )
on conflict (region, sub_region, area_detail) do update
set
  source_prefix = excluded.source_prefix,
  seed_urls = excluded.seed_urls,
  seed_titles = excluded.seed_titles,
  status = excluded.status,
  priority = excluded.priority;

notify pgrst, 'reload schema';
